<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
	<h1>Search products</h1>
	<p><?php echo $this->tag->linkTo(["products/new", "Create products"]) ?></p>
</div>

<?php echo $this->getContent() ?>

<?php echo $this->flash->output() ?>

<form action="/products/search" class="form-horizontal" method="get">
	<div class="form-group">
		<label for="fieldId" class="col-sm-2 control-label">Id</label>
		<div class="col-sm-10">
			<?php echo $this->tag->textField(["id", "type" => "number", "class" => "form-control", "id" => "fieldId"]); ?>
		</div>
	</div>

	<div class="form-group">
		<label for="fieldQuantity" class="col-sm-2 control-label">Quantity</label>
		<div class="col-sm-10">
			<?php echo $this->tag->textField(["quantity", "type" => "number", "class" => "form-control", "id" => "fieldQuantity"]); ?>
		</div>
	</div>

	<div class="form-group">
		<label for="fieldAddress" class="col-sm-2 control-label">Address</label>
		<div class="col-sm-10">
			<?php echo $this->tag->textField(["address", "size" => 30, "class" => "form-control", "id" => "fieldAddress"]); ?>
		</div>
	</div>

	<div class="form-group">
		<label for="fieldShippingdate" class="col-sm-2 control-label">ShippingDate</label>
		<div class="col-sm-10">
			<?php echo $this->tag->textField(["shippingDate", "size" => 30, "class" => "form-control", "id" => "fieldShippingdate"]); ?>
		</div>
	</div>

	<div class="form-group">
		<label for="fieldOrdercode" class="col-sm-2 control-label">OrderCode</label>
		<div class="col-sm-10">
			<?php echo $this->tag->textField(["orderCode", "size" => 30, "class" => "form-control", "id" => "fieldOrdercode"]); ?>
		</div>
	</div>


	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
		</div>
	</div>
</form>
