<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
	<nav>
		<ul class="pager">
			<li class="previous"><?php echo $this->tag->linkTo(["products", "Go Back"]) ?></li>
		</ul>
	</nav>
</div>

<div class="page-header">
	<h1>Create products</h1>
</div>

<?php echo $this->getContent(); ?>

<form action="/products/create" class="form-horizontal" method="post">
	<div class="form-group">
		<label for="fieldQuantity" class="col-sm-2 control-label">Quantity</label>
		<div class="col-sm-10">
			<?php echo $this->tag->textField(["quantity", "type" => "number", "class" => "form-control", "id" => "fieldQuantity"]); ?>
		</div>
	</div>

	<div class="form-group">
		<label for="fieldAddress" class="col-sm-2 control-label">Address</label>
		<div class="col-sm-10">
			<?php echo $this->tag->textField(["address", "size" => 30, "class" => "form-control", "id" => "fieldAddress"]); ?>
		</div>
	</div>

	<div class="form-group">
		<label for="fieldShippingdate" class="col-sm-2 control-label">ShippingDate</label>
		<div class="col-sm-10">
			<?php echo $this->tag->textField(["shippingDate", "size" => 30, "class" => "form-control", "id" => "fieldShippingdate"]); ?>
		</div>
	</div>

	<div class="form-group">
		<label for="fieldOrdercode" class="col-sm-2 control-label">OrderCode</label>
		<div class="col-sm-10">
			<?php echo $this->tag->textField(["orderCode", "size" => 30, "class" => "form-control", "id" => "fieldOrdercode"]); ?>
		</div>
	</div>


	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
		</div>
	</div>
</form>
