
<?php

use Phalcon\Tag;

echo $this->flash->output() ?>

<main class="login-form">
	<div class="cotainer">
		<div class="row justify-content-center">
			<div class="col-md-8">
				<div class="card">
					<div class="card-header">Login</div>
					<div class="card-body">
						<form action="/users/login" method="post">
							<div class="form-group row">
								<label for="login_address" class="col-md-4 col-form-label text-md-right">E-Mail</label>
								<div class="col-md-6">
									<input type="email" id="login_address" class="form-control" name="login" required autofocus>
								</div>
							</div>

							<div class="form-group row">
								<label for="password" class="col-md-4 col-form-label text-md-right">Password</label>
								<div class="col-md-6">
									<input type="password" id="password" class="form-control" name="password" required>
								</div>
							</div>
							<?php echo Tag::form('session/login') ?>

							<input type='hidden' name='<?php echo $this->security->getTokenKey() ?>'
								value='<?php echo $this->security->getToken() ?>'/>
							<div class="col-md-6 offset-md-4">
								<button type="submit" class="btn btn-primary">
									Login
								</button>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>

</main>



